default: &default
  root_path: app/assets
  public_root_path: public
  cache_path: tmp/cache/viter
  entry_paths: []
  alias:
    abcs: ../public
  build:
    assetsInlineLimit: 0
    sourcemap: false
    assetsDir: assets
    brotliSize: true
development:
  <<: *default
  server:
    host: localhost
    port: 3036
test:
  <<: *default
production:
  <<: *default
